[package]
name = "pepeaudio-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait = "0.1"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
pepeaudio-api = { path = "../pepeaudio-api" }
pepeaudio-core = { path = "../pepeaudio-core" }
pepeaudio-player = { path = "../pepeaudio-player" }
pepeaudio-storage = { path = "../pepeaudio-storage" }
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
tracing = "0.1"
uuid.workspace = true

[dev-dependencies]
time = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "test-util"] }

[lints]
workspace = true
